// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using week6Lab.Models.Repos;

namespace week6Lab.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20181205100934_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("week6Lab.Models.Message", b =>
                {
                    b.Property<int>("Key")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Msg");

                    b.Property<bool>("Priority");

                    b.Property<bool>("Reply");

                    b.Property<string>("Subject");

                    b.Property<DateTime>("TimeSent");

                    b.Property<int>("UserKey");

                    b.HasKey("Key");

                    b.HasIndex("UserKey");

                    b.ToTable("DBMessage");
                });

            modelBuilder.Entity("week6Lab.Models.Messages.User", b =>
                {
                    b.Property<int>("UserKey")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Fname");

                    b.Property<string>("Lname");

                    b.HasKey("UserKey");

                    b.ToTable("User");
                });

            modelBuilder.Entity("week6Lab.Models.Message", b =>
                {
                    b.HasOne("week6Lab.Models.Messages.User", "User")
                        .WithMany()
                        .HasForeignKey("UserKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
